# Generated by Django 5.0.3 on 2024-04-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parents",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="children", to="products.category"
            ),
        ),
    ]
