# Generated by Django 5.0.3 on 2024-04-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_category_parents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parents",
            field=models.ManyToManyField(
                related_name="children", to="products.category"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="shop_images/"),
        ),
    ]
