# Generated by Django 5.0.3 on 2024-04-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_category_parents_alter_shop_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["title"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="parents",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="children", to="products.category"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
